services:
  server:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - auth_service

  auth_service:
    image: quay.io/keycloak/keycloak
    command: start-dev
    ports:
      - "3001:8080"
    environment:
      - KEYCLOAK_ADMIN=keycloak
      - KEYCLOAK_ADMIN_PASSWORD=keycloak
